# Konfigurasjon for prosjekt-repo
title: ASR dokumentasjon
description: Aktiviteter og arbeid ifb ASR 
theme: jekyll-theme-minimal
baseurl: "/ASR"  # Husk skråstrek foran, men IKKE bak
url: "https://digdir.github.io"
